#:schema https://github.com/YunoHost/apps/raw/master/schemas/config_panel.v1.schema.json

version = "1.0"

[main]
name = "Hotglue configuration"

    [main.hotglue]
    name = "Editing credentials"
        [main.hotglue.admin]
        ask = "Set username"
        type = "string"
        optional = false
        help = "Cannot be empty"

        [main.hotglue.password]
        ask = "Set password"
        type = "password"
        optional = true
        visible = "username"
        help = "If a password already exists, leave blank and it will not be replaced."

