#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "hotglue"
name = "Hotglue app"
description.en = "HOTGLUE is a Content Manipulation System which allows to construct websites directly in a web-browser."

version = "1.4~ynh1"

maintainers = ["k0a1a"]

[upstream]
license = "GNU GENERAL PUBLIC LICENSE"
website = "https://hotglue.me"
demo = "https://hotglue.me/demo/"
admindoc = "https://discourse.superglue.it/c/hotglue"
userdoc = "https://discourse.superglue.it/c/hotglue"
code = "https://github.com/k0a1a/hotglue2"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

# FIXME: replace with true, false, or "not_relevant".
# Not to confuse with the "sso" key: the "ldap" key corresponds to wether or not a user *can* login on the app using
# its YunoHost credentials.
ldap = "true"

# FIXME: replace with true, false, or "not_relevant".
# Not to confuse with the "ldap" key: the "sso" key corresponds to wether or not a user is *automatically logged-in*
# on the app when logged-in on the YunoHost portal.
sso = "?"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/hotglue"

    [install.language]
    ask.en = "Choose the application language"
    type = "select"
    choices = ["en"]
    default = "en"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/k0a1a/hotglue2/archive/refs/tags/dev-release.zip"
    sha256 = "48fe7d5c6075a9729da038ad46e154a86a6c7f644306d88db761413cbbeeae4d"

    [resources.system_user]
    
    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2 php8.2-fpm php8.2-gd"