#!/bin/bash
# In simple cases, you don't need a config script.

# With a simple config_panel.toml, you can write in the app settings, in the
# upstream config file or replace complete files (logo ...) and restart services.

# The config scripts allows you to go further, to handle specific cases
# (validation of several interdependent fields, specific getter/setter for a value,
# display dynamic informations or choices, pre-loading of config type .cube... ).

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#REMOVEME? ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --key=install_dir)

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

set__password() {
    if [ "$password" == "" ]
    then
        ynh_app_setting_set --key=password --value="$password"
    fi
}

set__username() {
    if [ "$username" == "" ]
    then
        ynh_app_setting_set --key=username --value="$username"
    fi
}

ynh_app_config_validate() {
    _ynh_app_config_validate

    if [ "$username" == "" ]
    then
        ynh_die "You need to set a username"
    fi
}

ynh_app_config_apply() {
    _ynh_app_config_apply

    if [ ! "$password" == ""  ] && [ ! "$username" == "" ]
    then
      sed -i "s/\('AUTH_USER', '\).*\('\)/\1$username\2/g" "$install_dir/user-config.inc.php" &&
      sed -i "s/\('AUTH_PASSWORD', '\).*\('\)/\1$password\2/g" "$install_dir/user-config.inc.php"
    fi
}

#=================================================
ynh_app_config_run "$1"
